# Generated by Django 4.1.7 on 2023-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyone_in_touch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-lesson_price',), 'verbose_name': 'a teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('ES', 'Spanish'), ('FR', 'French')], max_length=3),
        ),
    ]
