# Generated by Django 4.1.7 on 2023-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyone_in_touch', '0002_alter_teacher_options_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(choices=[('English', 'ENG'), ('Spanish', 'ES'), ('French', 'FR')], max_length=32),
        ),
    ]
