# Generated by Django 4.1.7 on 2023-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyone_in_touch', '0003_alter_teacher_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='url',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(choices=[('English', 'ENG'), ('Spanish', 'ES'), ('French', 'FR')], default='ENG', max_length=32),
        ),
    ]
