# Generated by Django 4.1.7 on 2023-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyone_in_touch', '0004_teacher_url_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='url',
            field=models.SlugField(),
        ),
    ]
